#.github/workflows/tests.yaml
name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  pyTest:
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    runs-on: "ubuntu-latest"
    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install pytest
      - name: Run Tests
        run: python -m pytest -v --timeout=60
